name: Build and Deploy CV

on:
  push:
    branches: [main, master]
    paths:
      - 'template/**'
      - 'template/cv.typ'
      - 'template/cv_cn.typ'
      - 'lib.typ'
      - 'typst.toml'
      - '.github/workflows/build-and-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest

      - name: Build PDFs
        run: |
          typst compile template/cv.typ cv.pdf
          typst compile template/cv_cn.typ cv_cn.pdf

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload PDFs to S3
        run: |
          aws s3 cp cv.pdf s3://${{ secrets.S3_BUCKET }}/cv.pdf
          aws s3 cp cv_cn.pdf s3://${{ secrets.S3_BUCKET }}/cv_cn.pdf
